#spring.application.name=payment_service
#
## Port
#server.port = 8080
#
## DataSource
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/payment_db
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver

server:
  port: 8080

spring:
  application:
    name: payment_service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/payment_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.type: true
      hibernate.use_sql_comments: true
